### ISSUE TITLE
Unable to start locally due to dependency

### ISSUE THREAD

**Issue by robertbenjamin** [aupac/ember-aupac-typeahead#52]
`ember-cli-htmlbars` seems to expect `ember` to be in `bower.json`. Without that bower dependency, running `ember serve` results in a crash due to a missing dependency of `ember-template-compiler`:

```
Cannot find module '/Users/robertbenjamin/Work/ember-aupac-typeahead/bower_components/ember/ember-template-compiler'
Error: Cannot find module '/Users/robertbenjamin/Work/ember-aupac-typeahead/bower_components/ember/ember-template-compiler'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Class.htmlbarsOptions (/Users/robertbenjamin/Work/ember-aupac-typeahead/node_modules/ember-aupac-control/node_modules/ember-cli-htmlbars/ember-addon-main.js:70:25)
```

I'm at a bit of a loss for how to move forward, even the updated releases of `ember-cli-htmlbars` seems to still rely on using a Bower-installed version of Ember for the template compiler. If anyone has any suggestions for fixes (or if I'm missing something), I'm all ears.

**Comment by jackmatt2** [comment]
Can you give more context? Are you attempting to removed bower from ember-cli?
